# Generated by Django 4.1.3 on 2022-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('date_of_listing', models.DateField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('torque', models.PositiveIntegerField(blank=True, null=True)),
                ('sixty_mph', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bidding_status', models.CharField(max_length=255)),
                ('date_listing_ends', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'car',
                'verbose_name_plural': 'cars',
            },
        ),
    ]
